name: Block PRs From Develop

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prevent-develop-source:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is from develop branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" == "develop" ]; then
            echo "NOK: Pull requests from 'develop' branch are not allowed."
            exit 1
          else
            echo "OK: Source branch is allowed."
          fi
